baseURL = "https://hacksussex.co.uk/"
languageCode = "en-gb"
title = "HackSussex"
theme = "2019"

[social]
	facebook	= "https://www.facebook.com/hacksussex"
	twitter		= "https://twitter.com/hacksussex"

[params]
	images = ["/uploads/2018/11/Basic.png"]
